### ISSUE TITLE
Texto costumizado de sharing para FB, TW 

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#121]
Poner campo en markdown de posts para texto a compartir de tweet y texto a compartir FB. Ahora toma el título del post tal cual. 

Luego puedo poner lo textos: https://docs.google.com/document/d/1s2SS6DbweaLpvAhFgM9kUzlbHrd_ZJRP78QmvEKtSUY/edit

**Comment by carlosmaya** [comment]
no aplica
