### ISSUE TITLE
Se repite la forma de suscripción en las historias

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#144]
http://datos.gob.mx/historias/educacion/

![doblesub](https://cloud.githubusercontent.com/assets/705860/5944191/b793ab00-a6ea-11e4-8a4d-e84fbe87abcc.png)

**Comment by simiographics** [comment]
FUU

**Comment by carlosmaya** [comment]
@rodowi en la version actual ya no se presenta, aunque no logre ver en que PR se resolvió
