### ISSUE TITLE
Hello Maggie WTF

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#155]
![screen shot 2015-02-19 at 2 12 35 pm](https://cloud.githubusercontent.com/assets/6226604/6275007/70b2a174-b841-11e4-8693-5a26617581e5.png)

:construction:

**Comment by simiographics** [comment]
http://tclhost.com/bofEZd2.gif

**Comment by diegobeauroyre** [comment]
lol

**Comment by simiographics** [comment]
Removed 3bf6d1dcd621d00c5e3701e50fa4e887be2e81bb

**Comment by rodowi** [comment]
epic
