### ISSUE TITLE
Agregar Avance de la Red 

### ISSUE THREAD

**Issue by fer-gandara** [mxabierto/dgm#181]
Hey @diegobeauroyre aquí te va el markdown de la historia del lanzamiento de la red.

nota: si le das edit al texto, verás el markdown.

**Comment by fer-gandara** [comment]
# Red México Abierto: inicios, logros y desafíos

##### Por: Ana Francisca Vega

Desde Melbourne hasta [Xalapa](http://mxabierto.github.io/ng-ckan/#/instituciones/ayuntamiento-de-xalapa), Santiago de Chile, pasando por Madrid, Bogotá, Filadelfia o Zapopan, en el mundo hay cada vez más gobiernos locales que han comenzado a abrir su información pública para consulta, uso y reutilización. A pesar de que los casos y sus contextos son todos muy distintos, basta con echar una mirada rápida para encontrar que existen entre ellos algunos desafíos comunes. Uno de los más importantes tiene que ver con los costos asociados – percibidos o reales – del proceso mismo de apertura de datos. 

Prácticamente todos los gobiernos locales en algún punto de sus procesos de apertura se han hecho preguntas como: ¿qué datos tengo en mi resguardo? ¿qué datos debo abrir? ¿cómo lo hago? ¿cuánto me va a costar? ¿qué recursos humanos  y técnicos necesito? ¿cómo me hago de esos recursos? Encontrar las respuestas a algunas de esas preguntas puede significar para los gobiernos locales una buena pérdida de tiempo y recursos de por sí escasos.

Pensando en estos desafíos comunes y en la mejor forma de abordarlos, desde el Gobierno de la República ha surgido una iniciativa que propone una avenida mucho más rápida y eficiente para que los gobiernos municipales y estatales del país puedan abrir sus datos. Para ello, se impulsó la creación de la [Red México Abierto](http://mxabierto.org), una plataforma que permite a los distintos niveles de gobierno compartir sus experiencias y aprendizajes en torno a la apertura de datos de una forma sencilla y abierta. Como parte del proyecto, y con apoyo del Programa de Política Económica de México (PROPEM) de USAID, se elaboró también un [kit](http://mxabierto.org/implementacion.html) para que municipios y gobiernos estatales encuentren las herramientas y el apoyo necesarios para elaborar o profundizar su política de datos abiertos. A través del [kit](http://mxabierto.org/implementacion.html) y de la experiencia de formar parte de la Red, funcionarios públicos locales y estatales encargados de implementar la política de datos abiertos, están trabajando para abrir más conjuntos de datos en beneficio de la ciudadanía y de su propio ejercicio de gobierno.
A partir de un programa piloto en el que participaron 4 gobiernos municipales y 3 estatales y como parte del [kit](http://mxabierto.org/implementacion.html) de [Red México Abierto](http://mxabierto.org), se creó la Guía de Implementación para Datos Abiertos Locales y Estatales con la idea de que funcionarios de gobiernos municipales y estatales en México cuenten con una hoja de ruta clara que les permita abrir sus datos. Esta Guía se basó en el camino ya recorrido por la administración pública federal durante la creación de la plataforma [datos.gob.mx](http://mxabierto.github.io/ng-ckan/#/instituciones) – la primera iniciativa en su tipo a nivel nacional en el país– y se fue adaptando a las necesidades que el equipo coordinador del piloto iba distinguiendo conforme fue avanzando el piloto. 
De esta forma, desde el punto de vista del gobierno, los municipios y estados en México cuentan hoy con una sólida plataforma tecnológica común para subir sus conjuntos de datos, una Guía comprensiva para hacerlo, un foro para compartir mejores prácticas y un creciente conjunto de normas y licencias homologadas para implementar sus políticas de datos abiertos.
La creación de [Red México Abierto](http://mxabierto.org) es un paso en la dirección correcta. Falta camino por recorrer, sí, sin duda. Quedan desafíos importantes en temas que tienen que ver, por ejemplo, con la socialización y difusión de estos esfuerzos para que cada vez más ciudadanos - y las propias autoridades - reutilicen y aprovechen los datos abiertos. Hay que seguir trabajando también con las autoridades locales para que una vez que abran sus primeros conjuntos de datos, continúen abriendo más y  mejorando la calidad y pertinencia de la información que ponen a disposición de sus ciudadanos. Para ello, ha sido y continuará siendo invaluable la participación de algunas organizaciones sociales que han hecho de los datos abiertos y, en general, de los temas de gobierno digital, una bandera. 
Confiamos en que la presentación de [Red México Abierto](http://mxabierto.org) y los resultados de su programa piloto, contribuyan a que los gobiernos locales en México se acerquen al tema y lo incorporen como parte central de una nueva forma de gobernar y hacer política. Hoy, por cierto, los ciudadanos no esperan menos.

**Ana Francisca Vega es periodista y Open Data Specialist/USAID. Ana Francisca participó en la creación del kit y es parte del equipo coordinador de Red México Abierto.**

**Comment by diegobeauroyre** [comment]
#182
