### ISSUE TITLE
Cambiar posición del video en el post Red México Abierto

### ISSUE THREAD

**Issue by fer-gandara** [mxabierto/dgm#184]
@diegobeauroyre Esta raro el video en medio del texto, creo que lo podríamos poner hasta arriba, antes de iniciar la historia.

*ver preview

![image](https://cloud.githubusercontent.com/assets/9438963/6406141/26c1a176-bdf2-11e4-94ea-ae19fc411770.png)

**Comment by carlosmaya** [comment]
@fer-gandara @diegobeauroyre  ¿todavía hay que hacerlo?
