### ISSUE TITLE
Participa en el Consejo Consultivo de Datos Abiertos

### ISSUE THREAD

**Issue by fer-gandara** [mxabierto/dgm#195]
@diegobeauroyre aquí va el post sobre el Consejo Consultivo 

```
---
published: true
layout: "post-progress"
title: 'Participa en el Consejo Consultivo de Datos Abiertos’

excerpt: "El día de hoy, con motivo de la publicación Decreto de Datos Abiertos, el Gobierno de la República presenta la Versión 2.0 de la plataforma [datos.gob.mx](http://datos.gob.mx). Esta nueva versión inicia con Datos Abiertos de 22 Dependencias y Secretarías Federales, 2 estados y 3 municipios."
date: 2015-03-04
cover: "avances/dataton-xalapa/dataton-xalapa-cover.png"
cover_photo: "avances/dataton-xalapa/dataton-xalapa-cover_photo.png"
permalink: "avances/participaconsejoconsultivo"
section: avances
category: noticias
category_title: Noticias
tags: 
  - Consejo Consultivo
  - Datos Abiertos
---

```

**Propuesta de convocatoria para las expresiones de interés en formar parte del Consejo Consultivo de Datos Abiertos:**

El Consejo Consultivo de Datos Abiertos es un mecanismo de participación multidisciplinaria y plural de la sociedad civil, academia e industria, y tiene como objetivo verificar el cumplimiento, hacer recomendaciones, e incentivar la implementación y evaluación de la política de Datos Abiertos.
De acuerdo a las [Reglas de Operación del Consejo](http://tablero.gobabiertomx.org/files/54385ce88d4d9.pdf), se convoca a las organizaciones e interesados de todos los sectores de la sociedad a **expresar su interés en participar en el primer el primer ciclo de renovación de la membresía.** 

Esta convocatoria estará abierta del 4 al 25 de marzo de 2015. Una vez cerrada esta primera etapa, se integrará el Consejo para iniciar las etapas de evaluación, selección y publicación de resultados.

#### Te invitamos a participar en este ejercicio de colaboración entre sociedad y gobierno dando click [aquí](http://tablero.gobabiertomx.org/files/54385ce88d4d9.pdf).

Conoce más sobre el Consejo Consultivo de Datos Abiertos en:
* http://datos.gob.mx/avances/consejo-consultivo/
* http://tablero.gobabiertomx.org/
* http://pa2015.mx/

**Comment by fer-gandara** [comment]
@diegobeauroyre  esto es lo que estás buscando con Enrique

**Comment by diegobeauroyre** [comment]
@fer-gandara mmm los metadatos de este no son los nuevos

**Comment by diegobeauroyre** [comment]
Quedaría así:

---
layout: "post-progress"
published: true
featured: true
featured_tagline: 'Avance:'
title: 'Participa en el Consejo Consultivo de Datos Abiertos'
excerpt: "El día de hoy, con motivo de la publicación Decreto de Datos Abiertos, el Gobierno de la República presenta la Versión 2.0 de la plataforma [datos.gob.mx](http://datos.gob.mx). Esta nueva versión inicia con Datos Abiertos de 22 Dependencias y Secretarías Federales, 2 estados y 3 municipios."
date: 2015-03-04
cover: "avances/participaccc/participacc-cover.png"
cover_photo: "avances/participacc/participacc-cover_photo.png"
permalink: "avances/participacc.html"
section: avances
category: noticias
category_title: Noticias
tags: 
  - Consejo Consultivo
  - Datos Abiertos
---


**Propuesta de convocatoria para las expresiones de interés en formar parte del Consejo Consultivo de Datos Abiertos:**

El Consejo Consultivo de Datos Abiertos es un mecanismo de participación multidisciplinaria y plural de la sociedad civil, academia e industria, y tiene como objetivo verificar el cumplimiento, hacer recomendaciones, e incentivar la implementación y evaluación de la política de Datos Abiertos.
De acuerdo a las [Reglas de Operación del Consejo](http://tablero.gobabiertomx.org/files/54385ce88d4d9.pdf), se convoca a las organizaciones e interesados de todos los sectores de la sociedad a **expresar su interés en participar en el primer el primer ciclo de renovación de la membresía.** 

Esta convocatoria estará abierta del 4 al 25 de marzo de 2015. Una vez cerrada esta primera etapa, se integrará el Consejo para iniciar las etapas de evaluación, selección y publicación de resultados.

#### Te invitamos a participar en este ejercicio de colaboración entre sociedad y gobierno dando click [aquí](http://tablero.gobabiertomx.org/files/54385ce88d4d9.pdf).

Conoce más sobre el Consejo Consultivo de Datos Abiertos en:
* http://datos.gob.mx/avances/consejo-consultivo/
* http://tablero.gobabiertomx.org/
* http://pa2015.mx/

**Comment by fer-gandara** [comment]
Ok, va @diegobeauroyre. Súper.
