### ISSUE TITLE
Subir entrada Infraestructura Estratégica

### ISSUE THREAD

**Issue by fer-gandara** [mxabierto/dgm#196]
@diegobeauroyre @rodowi 

Título: Apertura de la Infraestructura Estratégica de Datos Abiertos a comentarios públicos

El 21 de febrero entró en vigor el *[Decreto que Establece la Regulación en Materia de Datos Abiertos](http://www.dof.gob.mx/nota_detalle.php?codigo=5382838&fecha=20/02/2015)*, el cual instruye a priorizar la publicación de Datos Abiertos con base en la demanda ciudadana. 
Con este motivo, se creó la Infraestructura Estratégica de Datos Abiertos –la base de los conjuntos de datos de alto valor para la población, y que será la guía para la priorización de los Datos Abiertos de las dependencias y entidades de la Administración Pública Federal, que serán publicados en [datos.gob.mx](http://datos.gob.mx/).

**Para construir este listado de manera conjunta con la ciudadanía, publicamos las categorías y conjuntos de datos prioritarios sugeridos en el primer borrador, para recibir comentarios públicos.** 

**Este ejercicio estará abierto del 18 de marzo, al 18 de abril de 2015, y tu opinión ayudará a definir los siguientes pasos y procesos de la iniciativa de Datos Abiertos en México.**

**Te invitamos a participar en esta iniciativa dando click [aquí](http://www.gob.mx/participa/docs/infraestructura-estrategica-de-datos-abiertos).**

**Comment by diegobeauroyre** [comment]
@fer-gandara ok pongo los metadatos? o #queonda

**Comment by fer-gandara** [comment]
@diegobeauroyre  aquí van, faltan imagenes y unos links a participa cuando este listo.
---
layout: "post-progress"
published: true
featured: true
featured_tagline: 'Avance:'
title: 'Apertura de la Infraestructura Estratégica de Datos Abiertos a comentarios públicos'
excerpt: "Se creó la Infraestructura Estratégica de Datos Abiertos –la base de los conjuntos de datos de alto valor para la población, que ayudarán a determinar el desarrollo económico y social, y que son necesarios para impulsar la innovación, detonar mayor eficiencia gubernamental e incrementar la transparencia y rendición de cuentas en nuestro país."
date: 2015-03-03
cover: "avances/red-mexico-abierto/red-mexico-abierto-cover.png"
cover_photo: "avances/red-mexico-abierto/red-mexico-abierto-cover_photo.png"
permalink: "avances/infraestructura-de-datos.html"
section: avances
category: noticias
category_title: Noticias
tags: 
  - Infraestructura Estratégica
  - Participación
  - Datos Abiertos 
---

**Comment by diegobeauroyre** [comment]
:ok_hand: 

Lo único que voy a cambiar es quitarle el bold al link porque es redundante. ¿qué dices?

**Comment by fer-gandara** [comment]
@diegobeauroyre De acuerdo ";)"

**Comment by rodowi** [comment]
@fer-gandara el issue debería llamarse "Subir historia de blah blah blah", y en los comentarios hablar sobre el markdown y los links que faltan.

**Comment by fer-gandara** [comment]
@diegobeauroyre aquí :dancer:
