### ISSUE TITLE
Post Xalapa México Abierto 

### ISSUE THREAD

**Issue by fer-gandara** [mxabierto/dgm#209]
````
Va markdown. Falta gregar metadatos. 

````
#### Experiencia, aciertos y áreas de oportunidad

El 1 de enero del 2014, iniciamos con la actual administración y se planteó la necesidad de comenzar a implementar nuevos mecanismos que integren a la ciudadanía en el proceso de toma de decisiones, que fomenten su participación y que apoyen la generación de una economía digital en nuestro municipio.

Es por ello que bajo la iniciativa del Alcalde Américo Zúñiga Martínez, en el Departamento de Gobierno Electrónico de la Dirección de Buen Gobierno y Proyectos Especiales, nos dimos a la tarea de iniciar el proceso de Xalapa Abierta, que dio paso a la Política de Datos Abiertos y Gobierno Abierto por parte del H. Ayuntamiento de Xalapa. El proceso que llevamos a cabo tuvo como primer paso un censo de datos y bases prioritarias.

Mediante el censo de datos y bases prioritarias  realizamos un análisis comparativo en el que revisamos por una parte, portales de Datos Abiertos de distintos gobiernos nacionales y subnacionales; mientras que por otro lado, también realizamos una investigación sobre la posible localización de información útil en el municipio. A partir de este análisis inicial, se determinaron las áreas prioritarias o las que habrían de generar mayor valor de acuerdo a otras iniciativas similares en distintas latitudes. De esta forma, llegamos a tomar las siguientes acciones:

**A. Operación**
De acuerdo a nuestro primer censo detectamos que varios de los datos prioritarios, se encontraban en resguardo del Gobierno del Estado; por lo tanto realizamos una solicitud formal por escrito a nombre del Alcalde pidiendo acceso a los conjuntos de datos. Para lograrlo asistimos personalmente a cada dependencia, en las cuales fue necesario explicar el tema y los objetivos de la Política de Datos Abiertos.

**B. Alianzas**
Iniciamos con alianzas estratégicas con los dos actores clave:
* Coordinación de Estrategia Digital Nacional:  Xalapa fue el primer ayuntamiento piloto de la Red México Abierto. Apoyándonos de su Escuadrón de Datos, logramos abrir 8 conjuntos de datos; dicho equipo nos brindó asesoría y acompañamiento técnico para la "curación" y posterior publicación de los conjuntos de datos en el portal de datos.gob.mx.
* Universidad Veracruzana: La alianza fue establecida a través de la Facultad de Informática y Estadística. Esta resultó fundamental para la creación y funcionamiento del Comité Técnico Municipal para la liberación de los datos. Maestros y alumnos de dicha facultad se involucraron en el proyecto, lo cual nos permitió contar con un equipo de apoyo para cumplir con los lineamientos y estándares de la Política de Datos Abiertos y del portal oficial de datos.gob.mx.

**C. Publicación y aprovechamiento**
Una vez publicados los primeros conjuntos de datos, realizamos el Hackatón Xalapa 2014. Este proyecto fue trabajado con meses de anticipación con el fin de dar a conocer los 8 conjuntos de datos publicados y a su vez, demostrar que se pueden aprovechar para generar valor e incidir en la mejora de la calidad de vida de nuestra ciudad capital. Tuvimos la participación de 400 personas en las conferencias, 150 se registraron y participaron durante las 70 horas de duración del Hackatón.

De acuerdo a nuestra experiencia dentro de la Red México Abierto enlistamos los aciertos y las áreas de oportunidad detectadas:

**Aciertos**
* **Apoyo del Ejecutivo:** Fue fundamental contar con el soporte e impulso del Alcalde en este tema, ya que nos facilitó el proceso para conseguir las bases de datos estatales y municipales.
* **Alianzas:** La búsqueda e integración de alianzas, nos ayudó a la obtención de más información y datos, asesoría y apoyo técnico. Lo cual se tradujo en una mayor penetración de la iniciativa de Datos Abiertos en la agenda a nivel local.

**Áreas de oportunidad**
* **Capacitación para el aprovechamiento:** Debido a la novedad del tema, los participantes del Hackatón, no contaban aún con la experiencia, ni ciertas habilidades necesarias para el mejor aprovechamiento y reutilización de los datos. Por esto considero que a la par de próximas aperturas se deben de impartir cursos y talleres proporcionen de herramientas, estrategias y mejores prácticas para la reutilización de los Datos Abiertos para el personal de gobierno y sobretodo ciudadanos en general.
* **Calidad vs. Oportunidad:** Nos estamos dando a la tarea de mejorar la calidad de la información publicada y de realizar análisis previos a la publicación de los mismos. Ya que de los 8 conjuntos de datos liberados para el Hackatón, detectamos posteriormente, que dos de estos conjuntos, no contaban con la información completa.

**¿Qué sigue para Xalapa en Datos Abiertos?**

* **Escuadrón de Datos Municipales:** Acabamos de crear nuestro Escuadrón de Datos, el cual se encargará de generar lineamientos, detección de datos, estandarización y publicación de los mismos.
* **Capacitación:** Llevaremos a cabo cursos y talleres de capacitación para la reutilización de los datos, enfocados a cualquier ciudadano, con el objetivo de que sean aprovechados para generar valor y demostrar su utilidad. El primer curso se llevó a cabo el día 21 de febrero y fue impartido por la Escuela de Datos. Se lanzó una convocatoria con 40 lugares, los cuales fueron cubiertos en 9 horas. Esto nos habla del interés que hay alrededor de esta iniciativa.

**Comment by fer-gandara** [comment]
Van metadatos @diegobeauroyre 
---
layout: "post-progress"
published: true
featured: true
featured_tagline: 'Avance:'
title: 'Xalapa: Aciertos y experiencias en Datos Abiertos'
excerpt: "Nos dimos a la tarea de iniciar el proceso de Xalapa Abierta, que dio paso a la Política de Datos Abiertos y Gobierno Abierto por parte del H. Ayuntamiento de Xalapa. El proceso que llevamos a cabo tuvo como primer paso un censo de datos y bases prioritarias."
date: 2015-03-11
cover: "avances/participacc/participacc-cover.png"
cover_photo: "avances/participacc/participacc-cover_photo.png"
permalink: "avances/xalapaproceso.html"
section: avances
category: noticias
category_title: Noticias
tags: 
  - Red México Abierto
  - Xalapa 
  - Datos Abiertos
---

**Comment by rodowi** [comment]
Merged in #212
