### ISSUE TITLE
Logos de instituciones no se ve en algunos casos

### ISSUE THREAD

**Issue by jipster** [mxabierto/dgm#220]
![image](https://cloud.githubusercontent.com/assets/5718530/6744058/e4078364-ce68-11e4-9339-d13de1687ffa.png)

**Comment by carlosmaya** [comment]
Se van a usar los logos del repo de assets 

https://github.com/mxabierto/assets/pull/5

**Comment by carlosmaya** [comment]
está reportado en mxabierto/ng-ckan#82
