### ISSUE TITLE
Quitar video de Red México Abierto de página principal dgm 

### ISSUE THREAD

**Issue by fer-gandara** [mxabierto/dgm#222]
@rodowi @diegobeauroyre ya podemos quitar el video de Red México Abierto.

**Comment by rodowi** [comment]
No sería bueno agregar una entrada en http://datos.gob.mx/avances/redmxabierto/ sobre el evento, y ahí dejar el video?

**Comment by diegobeauroyre** [comment]
#225 :monkey:
