### ISSUE TITLE
Apps: Cambiar Android Market por Google Play 

### ISSUE THREAD

**Issue by fer-gandara** [mxabierto/dgm#311]
Cambiar en botones para descargar la leyenda: Disponible en Android Market por Disponible en Google Play.

![image](https://cloud.githubusercontent.com/assets/9438963/8503852/a90bfa8a-218b-11e5-8bab-48b858428352.png)

@carlosmaya @diegobeauroyre

**Comment by carlosmaya** [comment]
al parecer no es una imagen, yo lo reviso
