### ISSUE TITLE
Actualizar link de Infraestructura de Datos en Acerca 

### ISSUE THREAD

**Issue by fer-gandara** [mxabierto/dgm#324]
Acerca: https://github.com/mxabierto/dgm/blob/c53bfb5b9dd11a7de92e72d8ef513cb2e07ec2fd/acerca.html

Link nuevo: http://www.gob.mx/consulta/docs/infraestructura-estrategica-de-datos-abiertos

![image](https://cloud.githubusercontent.com/assets/9438963/9051050/18d3ef9c-3a1b-11e5-8d81-fd7c76734d81.png)

@carlosmaya

**Comment by carlosmaya** [comment]
se queda como está
