### ISSUE TITLE
Sube App CONEVAL 

### ISSUE THREAD

**Issue by fer-gandara** [mxabierto/dgm#326]
---
published: true
layout: app

title: CONEVAL
date: 2015-08-07
cover: apps/obraabierta/obraabierta_cover.png (Cambiar por 
screenshots:
  - apps/obraabierta/obraabierta_1.png
  - apps/obraabierta/obraabierta_2.png
  - apps/obraabierta/obraabierta_3.png

links:
  appleStore: https://itunes.apple.com/mx/app/coneval/id1014997214?mt=8&ign-mpt=uo%3D4
  playStore: https://play.google.com/store/apps/details?id=mx.coneval.app

datasets:
 -
    title: "Bases de microdatos finales con indicadores de pobreza a nivel nacional y estatal, 2010, 2012 y 2014."
    url:  http://busca.datos.gob.mx/#/conjuntos/bases-de-microdatos-finales-con-indicadores-de-pobreza-a-nivel-nacional-y-estatal-2010-201-2014
 -
    title: "Indicadores de pobreza, 2010-2012"
    url:  http://busca.datos.gob.mx/#/conjuntos/indicadores-de-pobreza-2010-2012-nacional-y-estatal
 -
    title: "Inventario CONEVAL de Programas y Acciones Federales de Desarrollo Social"
    url:  http://busca.datos.gob.mx/#/conjuntos/inventario-coneval-de-programas-y-acciones-federales-de-desarrollo-social

app_author: Consejo Nacional de Evaluación de la Política de Desarrollo Social 

permalink: "/apps/coneval.html"
section: apps
category: movil
category_title: Móvil
tags:
  - Pobreza
  - Datos Abiertos

---

La aplicación móvil de CONEVAL es una herramienta de difusión de la información del Consejo que permite a los usuarios contar con los datos más relevantes que se generan en materia de medición de la pobreza a nivel nacional, estatal y municipal, y en evaluación de programas sociales.

**Comment by fer-gandara** [comment]
@chuckcfs @carlosmaya las imagenes están aquí: 

Portada: https://drive.google.com/open?id=0B2w-vs6q8_HaVGhPS044QldrUE0

Interior:  https://drive.google.com/open?id=0B2w-vs6q8_HaMDhpOURFWndTcG8

https://drive.google.com/open?id=0B2w-vs6q8_HaVGhPS044QldrUE0

https://drive.google.com/open?id=0B2w-vs6q8_HaRUZpTlQ2NFJqWVU

**Comment by carlosmaya** [comment]
closed by #328
