### ISSUE TITLE
Web app - Atlas Turístico de México

### ISSUE THREAD

**Issue by CarlosCCorr** [mxabierto/dgm#343]
published: true
layout: app

title: Atlas Turístico de México
date: 2015-09-17
cover: -cover.png
screenshots:
  - 1.png
  - 2.png
  - 3.png

links:
  web: http://atlasturistico.sectur.gob.mx/AtlasTuristico/bienvenido.do

datasets:
  -
    title:  Infraestructura aeroportuaria

    url:   http://busca.datos.gob.mx/#/conjuntos/infraestructura-aeroportuaria
    title:  Infraestructura marítima
    url:   http://busca.datos.gob.mx/#/conjuntos/infraestructura-maritima
 
app_author: Secretaría de Turismo

permalink: "/apps/atlasturistico.html"
section: apps
category: web
category_title: web
tags:
  - turismo
  - atlas
  - recursos naturales
  - cultura
—
El Atlas Turístico de México es el registro sistemático de carácter público de todos los bienes, recursos naturales y culturales que puedan constituirse en atractivos turísticos, sitio de interés y en general todas aquellas zonas y área territoriales de desarrollo Turístico.

**Comment by carlosmaya** [comment]
closed by #344
