### ISSUE TITLE
Diseño para sección de Acerca

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#349]

**Comment by diegobeauroyre** [comment]
Diseño de acerca Aquí: https://drive.google.com/folderview?id=0B6xuFjlJEb0NfkYyMUlDX3UxQnYwQTE3a0h3eEJYUzZJNzloSUZiRllBTmN0cmlpLXpjTlE&usp=sharing

@chuckcfs @carlosmaya
