### ISSUE TITLE
Diseño para opciones de Instituciones y Grupos en sección de Búsqueda

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#350]
![busqueda](https://cloud.githubusercontent.com/assets/2633527/9961688/7dcc76ae-5de7-11e5-961c-2c8ea30b202b.png)

**Comment by diegobeauroyre** [comment]
Diseño de grupos e instituciones (funcionan igual, sólo diferentes filtros) aquí https://drive.google.com/folderview?id=0B6xuFjlJEb0NfkYyMUlDX3UxQnYwQTE3a0h3eEJYUzZJNzloSUZiRllBTmN0cmlpLXpjTlE&usp=sharing
@carlosmaya @chuckcfs
