### ISSUE TITLE
Diseño de la vista detalles de datasets, con Metadatos y demas

### ISSUE THREAD

**Issue by chuckcfs** [mxabierto/dgm#352]

**Comment by diegobeauroyre** [comment]
@chuckcfs @carlosmaya  Una duda, ¿qué es *demás* exactamente? ¿Tienen un ejemplo de metadatos?

**Comment by carlosmaya** [comment]
actualmente solamente tenemos una vista con el listado de conjuntos

![screen shot 2015-09-22 at 9 53 09 am](https://cloud.githubusercontent.com/assets/2633527/10021888/c8b14d04-610f-11e5-9736-8618a2dd2b6f.png)

@chuckcfs creo que podemos usar el diseño de *resultados de búsqueda* y adaptarla para mostrar la lista de conjuntos, ¿cómo ves?

![busqueda instituciones interior](https://cloud.githubusercontent.com/assets/2633527/10021921/ebd7d884-610f-11e5-91f4-1a7b07257797.png)

**Comment by chuckcfs** [comment]
@diegobeauroyre @carlosmaya lo que pasa es que en el catálogo anterior la vista detalles de los datasets incluían los metadatos del mismo, en este momento no puedo entrar para sacar un screenshot pero viene una tabla con información del autor, email de contacto, fecha de modificación, etc. a esa tabla me refiero con el diseño de la vista de detalles con metadatos, de igual forma en las instituciones y grupos, ademas de los catálogos de datos en esa vista detalles se incluyen metadatos de las institución o grupo, ademas de los datasets
