### ISSUE TITLE
Agregar video en landing page

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#355]
Cuando el usuario le de clic en *CONOCE MÁS* se debe mostrar el video que actualmente está en Acerca

![screen shot 2015-09-25 at 8 03 36 pm](https://cloud.githubusercontent.com/assets/2633527/10114980/a33e3632-63c0-11e5-8226-0ba95c23bb6b.png)

**Comment by chuckcfs** [comment]
¿qué video es?

**Comment by fer-gandara** [comment]
No lo tenemos todavia. 

María Fernanda Gándara Gil 
@fer_gandara | +5218118809651

**Comment by carlosmaya** [comment]
va a ser un embed de youtube

**Comment by rodowi** [comment]
es el que ya existe de /acerca
