### ISSUE TITLE
La guía se ve colapsada

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#378]
Chrome 45

![screen shot 2015-09-28 at 10 15 41 am](https://cloud.githubusercontent.com/assets/705860/10139866/97ecf942-65ca-11e5-838e-29e03ebd8e92.png)

**Comment by carlosmaya** [comment]
Chrome 45

![screen shot 2015-09-29 at 7 14 23 pm](https://cloud.githubusercontent.com/assets/2633527/10181484/5e1f2112-66de-11e5-9113-e14cbb917639.png)

**Comment by chuckcfs** [comment]
@carlosmaya si se ve bien no?

**Comment by carlosmaya** [comment]
no se ha presentado de nuevo
