### ISSUE TITLE
Ligar los twits a hashtag #DatosAbiertos

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#379]

**Comment by rodowi** [comment]
SOLUCIÓN TEMPORAL: esconder el div de los tweets

**Comment by diegobeauroyre** [comment]
Cuando se ponga, hay que ligarlo a #DatosAbiertos sin MX

**Comment by carlosmaya** [comment]
@chuckcfs hay que habilitarlo de nuevo, ya se descarta la solución temporal

**Comment by chuckcfs** [comment]
@carlosmaya ok, lo meto, pero entonces es al hashtag, no a la cuenta, ¿correcto?

**Comment by carlosmaya** [comment]
correcto! .. al hashtag

**Comment by chuckcfs** [comment]
para los tweets en JSON creo que sería esta estructura

```
{
  content: 'Todas las dependencias...',
  author: 'SEGOB México',
  author_handler: '@SEGOB_mx',
  date: 'hace 3 días',
  avatar: 'http://twitter.com/....'
}
```

**Comment by rodowi** [comment]
2 comentarios
1) Agregué liga al tuit
2) date: pondremos la fecha tal como está en el tuit, y si es necesario automáticamente podemos parsearlo a 'hace 3 días' dinámicamente (aunque yo creo que es nice-to-have)

Algo así estoy armando:
```json
[
    {
        "content": "México lanza una plataforma para monitorear #ODS http://ow.ly/SVtFO #ObjetivosMundiales @DatosGobMx",
        "content_url": "https: //twitter.com/FundacionCIDEAL/status/649964666215645184",
        "autor": "FundaciónCIDEAL",
        "author_handler": "@FundacionCIDEAL",
        "date": "10: 10AM-2Oct2015",
        "avatar": "https: //pbs.twimg.com/profile_images/1576951710/logo_cideal_400x400.JPG"
    }
]
```
