### ISSUE TITLE
Agregar texto de descripción en secciones de Herramientas e Impacto

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#384]

**Comment by carlosmaya** [comment]
Herramientas  =>  mxabierto/dgm-content#2
Impacto  =>  mxabierto/dgm-content#3

**Comment by chuckcfs** [comment]
parece que ya esta

<img width="1403" alt="screen shot 2015-09-28 at 16 51 34" src="https://cloud.githubusercontent.com/assets/1383865/10149766/3a44acae-6601-11e5-9a8c-1be1ca72d0a3.png">

**Comment by carlosmaya** [comment]
ese mismo texto tiene que estar acá

* Herramientas

![screen shot 2015-09-29 at 7 17 06 pm](https://cloud.githubusercontent.com/assets/2633527/10181541/14cd9556-66df-11e5-99b1-df5bf8cf57a1.png)

* Impacto

![screen shot 2015-09-29 at 7 17 17 pm](https://cloud.githubusercontent.com/assets/2633527/10181543/1b586da6-66df-11e5-9a6e-e55b922d2356.png)

**Comment by chuckcfs** [comment]
aaaah ya entendí, lo agrego
