### ISSUE TITLE
Aplicar substring a descripciones cortas de contenido en Impacto

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#385]

**Comment by carlosmaya** [comment]
![screen shot 2015-09-28 at 11 11 34 am](https://cloud.githubusercontent.com/assets/2633527/10141381/cbab86fc-65d1-11e5-95ab-39e598799d2f.png)

**Comment by chuckcfs** [comment]
con que número de carácteres?

**Comment by carlosmaya** [comment]
closed by #408
