### ISSUE TITLE
Actualizar sub-secciones en Impacto

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#389]
- [ ] Casos de uso
- [ ] Noticias
- [ ] Avance

![impacto01](https://cloud.githubusercontent.com/assets/2633527/10143427/ec2b953c-65dd-11e5-9fe0-cf58532eb542.png)

**Comment by chuckcfs** [comment]
lo actualizo ya? hay posts de casos de uso? como se llama o se va a llamar la sección para "Casos de uso" en los metadatos de los posts?

**Comment by carlosmaya** [comment]
lo ponemos como

`sub_section: casos-de-uso`
