### ISSUE TITLE
Medio ambiente se corta en home 

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#396]
<img width="116" alt="screen shot 2015-09-28 at 1 42 36 pm" src="https://cloud.githubusercontent.com/assets/6226604/10145270/a174d616-65e7-11e5-82cb-57949c1f508b.png">

Se corta Medio Ambiente. Creo que podemos bajarle el tamaño a los íconos y ponerle menos interlineado a los nombres de los sectores:

<img width="776" alt="screen shot 2015-09-28 at 1 43 29 pm" src="https://cloud.githubusercontent.com/assets/6226604/10145218/6a3c6736-65e7-11e5-8e26-96908405c3d9.png">

**Comment by carlosmaya** [comment]
se presenta en **Safari 8** y **Chrome 45**

**Comment by diegobeauroyre** [comment]
También hay que checar la versión móvil de estos filtros: 

<img width="251" alt="screen shot 2015-10-01 at 11 53 23 am" src="https://cloud.githubusercontent.com/assets/6226604/10227470/1c7b5626-6833-11e5-9abf-f5c3701de7fc.png">

**Comment by carlosmaya** [comment]
@dhb el sitio no está para móviles
