### ISSUE TITLE
Agregar imágenes para slider de impacto

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#402]
Son tres historias:

[ ] Carta de Datos Abietos

![pnud_featured_photo-1280x440](https://cloud.githubusercontent.com/assets/6226604/10146350/0933a038-65ee-11e5-9ad1-f84b641c88ec.png)

[ ] Plataforma PNUD, agenda 2030

![opendatacharter_featured_photo-1280x440](https://cloud.githubusercontent.com/assets/6226604/10146349/093249a4-65ee-11e5-862e-24ed6eaa3290.jpg)

[ ] Alianza de Datos para el Desarrollo Sostenible

Las primeras dos ya tenemos las imágenes @pedrovallejo, pones aquí la tercera cuando la tengas?

**Comment by pedrovallejo** [comment]
![data_4sdgs-02](https://cloud.githubusercontent.com/assets/13205094/10146916/d361cf90-65f0-11e5-812e-1f512bfd5d87.png)
