### ISSUE TITLE
Agregar autor en la descripción breve que se muestra en la página de Herramientas

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#407]

**Comment by chuckcfs** [comment]
@carlosmaya ¿en cuál descripción breve?

**Comment by carlosmaya** [comment]
@chuckcfs 

![screen shot 2015-09-28 at 4 33 12 pm](https://cloud.githubusercontent.com/assets/2633527/10149418/200da248-65ff-11e5-9476-1fa19fe7a009.png)

**Comment by carlosmaya** [comment]
closed by #410
