### ISSUE TITLE
En Herramientas agregar sub-sección Otros para las que están como gov_app

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#440]
En esta sub-sección van a estar todas las que están como `section: gov_apps`

![screen shot 2015-10-05 at 7 25 39 pm](https://cloud.githubusercontent.com/assets/2633527/10297339/35577690-6b97-11e5-8b19-732cbe44ff49.png)

**Comment by chuckcfs** [comment]
@carlosmaya para esto falta categorizar los posts en `dgm-content`
