### ISSUE TITLE
Publicar en landing los posts marcados como "featured: true" de Herramienta y Avances

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#441]
![screen shot 2015-10-05 at 7 32 06 pm](https://cloud.githubusercontent.com/assets/2633527/10297401/ef550076-6b97-11e5-9828-57c6bb2cf505.png)

**Comment by chuckcfs** [comment]
@carlosmaya y si no hay `featured`

**Comment by carlosmaya** [comment]
la más reciente
