### ISSUE TITLE
Estandarizar medidas de imágenes 

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#451]

**Comment by carlosmaya** [comment]
- [x] Para Grid 760x440
- [ ] Alargadas ( primer post en grid, slider, header de posts )

**Comment by carlosmaya** [comment]
**Imagen de Grid**
![screen shot 2015-10-06 at 9 20 21 am](https://cloud.githubusercontent.com/assets/2633527/10311531/c2916956-6c0c-11e5-9cfe-f1ba44faf9da.png)

**Imagen primer post en grid**
![screen shot 2015-10-06 at 9 20 48 am](https://cloud.githubusercontent.com/assets/2633527/10311546/ceb31414-6c0c-11e5-866d-459ddc18a636.png)

**Imagen slider en landing page**
![screen shot 2015-10-06 at 9 21 11 am](https://cloud.githubusercontent.com/assets/2633527/10311557/dd521cf4-6c0c-11e5-9eb7-1f34e7e2e362.png)

**Imagen cover de posts**
![screen shot 2015-10-06 at 9 22 20 am](https://cloud.githubusercontent.com/assets/2633527/10311577/f6f8743c-6c0c-11e5-944a-161403901a3f.png)

**Imagen slider en post de herramientas**
![screen shot 2015-10-06 at 9 23 53 am](https://cloud.githubusercontent.com/assets/2633527/10311630/29997b16-6c0d-11e5-95be-772e8d919905.png)

**Comment by rodowi** [comment]
@diegobeauroyre necesitamos ayuda por aquí

**Comment by carlosmaya** [comment]
- [ ] 2200 x 764
- [ ] 760 x 440

**Comment by carlosmaya** [comment]
Acá están las imágenes

https://drive.google.com/folderview?id=0B6xuFjlJEb0NaHA4TkZ1TmtVTjQ&usp=sharing
