### ISSUE TITLE
Agregar el metadato landingPage A.K.A. diccionario de datos

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#452]
NICE TO HAVE para este sprint, aunque se enojen algunos millennials

<img width="830" alt="screen shot 2015-10-06 at 11 01 23 am" src="https://cloud.githubusercontent.com/assets/705860/10314407/2ad92b5e-6c1a-11e5-915c-6c0988cb9d6d.png">

**Comment by carlosmaya** [comment]
se mueve a mxabierto/ng-ckan#84
