### ISSUE TITLE
Poner sharing de navbar con texto e imagen

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#453]
Los íconos de redes te llevan al home de fb, tw, in, git no a un mensaje de sharing predeterminado.
<img width="245" alt="screen shot 2015-10-06 at 2 40 04 pm" src="https://cloud.githubusercontent.com/assets/6226604/10320250/28ea0a70-6c38-11e5-97fa-a2106eaba5f1.png">

**Comment by diegobeauroyre** [comment]
Necesitamos textos para este share, @fer-gandara ¿nos ayudas?

**Comment by carlosmaya** [comment]
¿y ya tenemos cuenta oficial de fb, tw e in ?  de hecho esos se quitaron, voy a revisar porque aparecen en esta version

**Comment by carlosmaya** [comment]
por la ubicación a mi me suena más a que son los sitios oficial a un ícono de share
