### ISSUE TITLE
Faltan botones en interior herramientas

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#454]
<img width="1267" alt="screen shot 2015-10-06 at 2 43 11 pm" src="https://cloud.githubusercontent.com/assets/6226604/10320400/ee339bf2-6c38-11e5-9e4b-24fdd9c924ba.png">

Son los de disponible en:

Web
Apple Store
Android 
Play etc.

<img width="864" alt="screen shot 2015-10-06 at 2 46 16 pm" src="https://cloud.githubusercontent.com/assets/6226604/10320445/19013772-6c39-11e5-902c-35034ce80e23.png">

**Comment by carlosmaya** [comment]
está relacionado al #450

**Comment by carlosmaya** [comment]
@chuckcfs este se resuelve con el #450
