### ISSUE TITLE
Poner info completa en conjuntos de datos utilizados en Herramientas.

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#455]
Como está ahora:

<img width="1019" alt="screen shot 2015-10-06 at 2 47 49 pm" src="https://cloud.githubusercontent.com/assets/6226604/10320489/4ff298a2-6c39-11e5-8457-d6436766880f.png">

Como es con más info:

<img width="612" alt="screen shot 2015-10-06 at 2 43 49 pm" src="https://cloud.githubusercontent.com/assets/6226604/10320501/61ff7ede-6c39-11e5-91d1-a2aebe9a7a80.png">

**Comment by carlosmaya** [comment]
@diegobeauroyre el tema aquí, es que en los posts existen varios conjuntos utilizados que todavía no están en **busca.datos.gob.mx** y la opción inmediata es incluir mas metadatos en el markdown para tener toda la info

**Comment by carlosmaya** [comment]
Por ejemplo, la herramienta de Mappir lleva la Institución en el `title` del conjunto

![screen shot 2015-10-06 at 6 10 08 pm](https://cloud.githubusercontent.com/assets/2633527/10325283/b30b944a-6c55-11e5-85b0-d3a36c9f41e6.png)
