### ISSUE TITLE
Headers de Herramientas e impacto no funcionan

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#456]
Propongo lo siguiente:
![herramientas copy](https://cloud.githubusercontent.com/assets/6226604/10321045/3c64d4a0-6c3c-11e5-840c-5ca351d25457.png)
![impacto copy](https://cloud.githubusercontent.com/assets/6226604/10321046/3c6e0782-6c3c-11e5-978c-b23ae4490ec6.png)

**Comment by chuckcfs** [comment]
como ven de esto @rodowi @carlosmaya ¿lo ponemos así?

**Comment by carlosmaya** [comment]
a mi me parece que usa mejor el espacio y no deja tanto hueco, yo digo que
si
