### ISSUE TITLE
No aparecen íconos de sectores en herramientas

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#457]
<img width="1256" alt="screen shot 2015-10-06 at 3 10 39 pm" src="https://cloud.githubusercontent.com/assets/6226604/10321102/8d69090c-6c3c-11e5-9af6-3c2d4e9392d1.png">

**Comment by carlosmaya** [comment]
esto es en Impacto y aplica para los que están categorizados como Otros

`category: otros`
