### ISSUE TITLE
Fijar max-height para imágenes en interiores de Herramientas

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#458]
También podemos pegar el div a la derecha siempre
Meter los botones de "Disponible en" en el div del título de la app tambien ayudaría.

Para que no pase esto:

<img width="1263" alt="screen shot 2015-10-06 at 3 33 28 pm" src="https://cloud.githubusercontent.com/assets/6226604/10321812/50fe3aec-6c40-11e5-8a4b-202eadec4686.png">

<img width="1072" alt="screen shot 2015-10-06 at 3 32 58 pm" src="https://cloud.githubusercontent.com/assets/6226604/10321826/5c985b30-6c40-11e5-95bd-884f1118363f.png">

<img width="1265" alt="screen shot 2015-10-06 at 3 24 19 pm" src="https://cloud.githubusercontent.com/assets/6226604/10321835/681f99fa-6c40-11e5-85e4-49912e98b914.png">

**Comment by chuckcfs** [comment]
@diegobeauroyre no entiendo que se supone que el `max-height` va a evitar, hay que definir el tamaño de las imagenes y esas medidas se deben respetar, mientras las imagenes sean de difrentes proporciones a menos que se distorsionen con CSS va a seguir pasando

**Comment by carlosmaya** [comment]
closed by #467
