### ISSUE TITLE
Agregar imágenes de los sectores como cover, con nombre de la herramienta

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#460]
![categoria-salud](https://cloud.githubusercontent.com/assets/6226604/10325854/b10242ac-6c5a-11e5-9201-9d3e37a843a4.png)

**Comment by diegobeauroyre** [comment]
No tengo permiso para pushear en assets entonces los puse aquí: https://drive.google.com/folderview?id=0B6xuFjlJEb0NNVVCbXo5Wnl5MHc&usp=sharing

**Comment by carlosmaya** [comment]
@diegobeauroyre  vemos solo 8 imágenes, creo que nos faltan 3

* Energía y medio ambiente
* Finanzas y contrataciones
* Gobiernos locales
