### ISSUE TITLE
Solo mostrar los sectores que tengan contenido

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#469]
Por ejemplo, Finanzas y Contrataciones

**Comment by chuckcfs** [comment]
pues de esto, acabo de checar y únicamente Finanzas y Contrataciones no tiene nada, podemos poner algunos artículos en esa categoría o quitarlo por completo, como tu veas

**Comment by carlosmaya** [comment]
@fer-gandara ¿crees que podamos agregar o categorizar algún post de Impacto como `Finanzas y Contrataciones` ?

**Comment by carlosmaya** [comment]
@chuckcfs  y si checamos los posts? 

```
{% assign posts = site.posts | where: 'section', include.section | where: 'category', include.category | where: 'published', true | sort: 'date' %}
{% if posts.size > 0 %}
```

**Comment by carlosmaya** [comment]
closed by #493
