### ISSUE TITLE
Agregar herramienta featured por sector

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#478]

**Comment by chuckcfs** [comment]
@carlosmaya este issue creo que se cierra con lo de las imágenes de sector

**Comment by carlosmaya** [comment]
nos está haciendo falta incluir un `brief` de la herramienta, anexo la imagen

![categoria-salud_1](https://cloud.githubusercontent.com/assets/2633527/10378861/09066ee8-6dd1-11e5-855c-a411668ee668.png)

**Comment by chuckcfs** [comment]
para esto me falta el texto de cada herramienta

**Comment by carlosmaya** [comment]
¿deberíamos agregar otro metadato llamado `brief` o `short_description` ? o podríamos hacer un extracto del contenido, no se que tanto afecte que algunos posts están con `markdown` y otros con `html`

**Comment by chuckcfs** [comment]
pues si se podría pero ves que ahorita la imagen es hardcoded, no es de ningún post




Sent from Mailbox

**Comment by carlosmaya** [comment]
Lo correcto sería que cada `featured` del sector tuviera su propia imagen de fondo, podríamos hacer ese cambio y las que ahorita tenemos como hardcoded ponerlas en el post correspondiente para que se muestren

**Comment by carlosmaya** [comment]
@chuckcfs esta es la relación de las herramientas de donde sacaron las imágenes para el cover de cada sector

Salud			       =>  herramientas/herramientas/2014-11-20-mortalidad-2014.md
Cultura y turismo   	       =>  herramientas/apps/2015-09-17-atlasturistico.md
Geoespacial		       =>  herramientas/apps/2015-02-09-cartografiaminera.md
Seguridad     		       =>  herramientas/herramientas/2015-07-22-PGR-2015.md
Educación		       =>  herramientas/herramientas/2015-02-20-cemabe-01.md
Economía		       =>  herramientas/herramientas/2014-10-01-IMSS-2014.md
Desarrollo sostenible      =>  herramientas/herramientas/2014-10-01-Coneval-2014.md
Infraestructura		        =>  herramientas/herramientas/2014-10-01-tampico-2013.md

**Comment by chuckcfs** [comment]
@carlosmaya ok, y la descripción? tomo algunas palabras (digamos 40) del contenido?

**Comment by carlosmaya** [comment]
si, hay que hacerlo así
