### ISSUE TITLE
Integrar comscore analytics

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#480]
¿qué métricas @jipster?

**Comment by jipster** [comment]
https://docs.google.com/spreadsheets/d/1yO0cntEhsKHWQ9BDQKk0P4AfgNfdLGL36SBXlNKgkvg/edit?usp=sharing

Jorge Díaz
Director de Participación y Comunidades
Coordinación de Estrategia Digital Nacional
Presidencia de la República
+52 55 50935300 ext. 7322


2015-10-08 12:06 GMT-05:00 rodowi <notifications@github.com>:
