### ISSUE TITLE
Agregar blur al GIF que esta en el background del landing page

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#500]

**Comment by chuckcfs** [comment]
@carlosmaya como blur? cambiar la opacidad del overlay o como? porque si es hacer un blur del GIF lo tiene que hacer @diegobeauroyre, yo no lo puedo hacer con CSS

**Comment by carlosmaya** [comment]
es hacer un efecto "blurry" del GIF que está como background, creo que es con esto en CSS `filter:blur`

**Comment by chuckcfs** [comment]
ok, lo checo pero me parece que el soporte del `filter` no es tan amplio
