### ISSUE TITLE
Registro a newsletter no funciona

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#504]
![dgm-504](https://cloud.githubusercontent.com/assets/2633527/10517572/f892b592-7322-11e5-8799-aa8eab560035.png)

**Comment by chuckcfs** [comment]
@carlosmaya puedes probar si con ese correo te deja en la versión actual de datos.gob.mx, porque me suena a que es cosa de mailchimp

**Comment by carlosmaya** [comment]
es cierto!!

![screen shot 2015-10-15 at 10 01 41 am](https://cloud.githubusercontent.com/assets/2633527/10518457/2c5ef4c2-7327-11e5-84ad-8cec5431db08.png)

**Comment by chuckcfs** [comment]
@carlosmaya entonces podemos cerrar el issue no?
