### ISSUE TITLE
Agregar link a los datasets publicados por la Institución

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#514]
![dgm-514](https://cloud.githubusercontent.com/assets/2633527/10597343/8eb07cf6-76b3-11e5-8f69-521f59264976.png)

**Comment by carlosmaya** [comment]
@chuckcfs estoy viendo que en ng-ckan todo el renglón es un link al dataset, creo que deberíamos hacerlo igual en estos casos

**Comment by chuckcfs** [comment]
@carlosmaya pero en este caso, esta el link al dataset y ademas hay que agregar el de la institución, no se puede lo del link de todo el renglón

**Comment by carlosmaya** [comment]
me refería a que no incluyéramos el link de la institución e hiciéramos todo el renglón un link al dataset ( incluso la fecha ), con eso atenderíamos la premisa del #505
