### ISSUE TITLE
Actualizar slider con historias de Impacto en landing page

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#515]
- [x] Agregar autor
- [x] Usar metadato `brief`o `short_description` para el texto
- [x] Aumentar a 5 las historias 
- [x] Quitar las sombras de los lados
- [x] Ajustar las imágenes a un mismo alto

![dgm-515](https://cloud.githubusercontent.com/assets/2633527/10597539/4d3c9d2a-76b5-11e5-942b-35ebf6665863.png)

**Comment by chuckcfs** [comment]
@carlosmaya voy a poner las imágenes con un `height` fijo, pero hay que ajustar las imágenes, no puedo hacer milagros, si siguen siendo de diferentes tamaños nunca se va a ver bien
