### ISSUE TITLE
Agregar opción para "Ver más tweets"

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#516]
Al momento de dar clic en el link se deben de mostrar los siguientes 3 tweets en la lista. Esto aplica para cuando en la lista curada hay más de 3 tweets

![dgm-516](https://cloud.githubusercontent.com/assets/2633527/10597631/2bcfa1ae-76b6-11e5-9e88-ffe6c3b9daee.png)

**Comment by chuckcfs** [comment]
@carlosmaya y a donde debe llevar este enlace?

**Comment by carlosmaya** [comment]
en realidad no te lleva a ningún lado, solo hace como un carrusel o slider de los siguientes 3 tweets desde el archivo donde están todos los "curados"

**Comment by chuckcfs** [comment]
ok, pero hay que actualizar ese archivo, sólo tengo 3 tweets

**Comment by carlosmaya** [comment]
se cambio por #619
