### ISSUE TITLE
Ajustar el alto de los cuadros de descripción de herramientas/impacto al mismo para todos

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#538]
![screen shot 2015-10-22 at 9 25 23 pm](https://cloud.githubusercontent.com/assets/2633527/10683103/9c33d4b6-7903-11e5-9c34-3eeec094ae75.png)

**Comment by chuckcfs** [comment]
@carlosmaya en que navegador te sucede esto?

<img width="1417" alt="screen shot 2015-10-26 at 11 47 09" src="https://cloud.githubusercontent.com/assets/1383865/10737376/6a5f42b4-7bd7-11e5-86ad-9d8f2616353f.png">

yo lo estoy viendo en firefox y esta bien, son del mismo alto, lo que es diferente son las imágenes pero es cosa editorial

**Comment by carlosmaya** [comment]
* Chrome Version 46.0.2490.80
* Safari Version 9.0.1 (11601.2.7.2)
