### ISSUE TITLE
Renombrar todas las imágenes

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#56]
Problema:
* Git se vuelve loco cuando hay acentos en los filenames
* Las imágenes tienen nombres nada descriptivos como "screenshot-2014-0..."

Solución
* No acentos
* Los nombres de las imágenes empezaran con el nombre de su carpeta
  * separado con -
  * sin acentos, i.e. cambiar á por a
* Agregar numeración incremental a dos dígitos 01, 02, 03 si existe más de una con el mismo nombre
* Si las imágenes son las mismas pero con diferentes resoluciones, se agrega como sufijo, p.ej. atlas-de-marginacion-1024x768.png

**Comment by carlosmaya** [comment]
se resolvión con #755 a través del CMS
