### ISSUE TITLE
Poner nuevos tamaños de header y primera sección 

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#566]
Con la nueva verisón del mock:

https://drive.google.com/folderview?id=0B6xuFjlJEb0NfkYyMUlDX3UxQnYwQTE3a0h3eEJYUzZJNzloSUZiRllBTmN0cmlpLXpjTlE&usp=sharing

Los textos tendrán un max. de 140 caracteres para no hacer todo muy alto.

**Comment by carlosmaya** [comment]
Ajustar para que lo que se muestre sea lo que se ve en la imagen

![dgm-566](https://cloud.githubusercontent.com/assets/2633527/10766459/47ce62f4-7c9d-11e5-8611-ad657fc7d865.png)
