### ISSUE TITLE
Ajustes en imágenes de slider impacto

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#602]
[ ] No se ve bien la del post de Tecnología Humanitaria, queda franja blanca a la derecha

<img width="1040" alt="screen shot 2015-11-03 at 6 19 24 pm" src="https://cloud.githubusercontent.com/assets/6226604/10925981/946ce98a-8258-11e5-8ebf-0907970084c2.png">

[ ] En móvil, en chrome se deforman las imágenes

<img width="394" alt="screen shot 2015-11-03 at 6 28 12 pm" src="https://cloud.githubusercontent.com/assets/6226604/10925998/aebd64fe-8258-11e5-8f26-c020591d856e.png">

**Comment by carlosmaya** [comment]
closed by #643
