### ISSUE TITLE
Poner imágenes de Gird para ODS e Hidrometerorológico

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#603]
<img width="1027" alt="screen shot 2015-11-03 at 6 29 57 pm" src="https://cloud.githubusercontent.com/assets/6226604/10926035/ea3d8054-8258-11e5-91a9-6328575a9881.png">

acá están las que irían;

![herramienta-ods_grid_photo-380x220](https://cloud.githubusercontent.com/assets/6226604/10926103/b2dc649e-8259-11e5-9b71-0fc5244f5fd6.jpg)

![hidrometeorologico_grid_photo-380x220](https://cloud.githubusercontent.com/assets/6226604/10926132/eb4844f6-8259-11e5-9000-e3c27c02aec3.jpg)

**Comment by carlosmaya** [comment]
closed by #652
