### ISSUE TITLE
Agregar cover images que faltan a impacto

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#606]
Están las imágenes acá: https://drive.google.com/folderview?id=0B6xuFjlJEb0Nemk1QUhTbDQ5Uzg&usp=sharing

Esto es para que no suceda esto al elegir los filtros de los sectores: 

<img width="1236" alt="screen shot 2015-11-03 at 7 15 44 pm" src="https://cloud.githubusercontent.com/assets/6226604/10926688/4e7500c8-825f-11e5-8207-45107c8d875c.png">

**Comment by carlosmaya** [comment]
closed by #643
