### ISSUE TITLE
Quitar franjas negras en video Acerca de 

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#607]
<img width="825" alt="screen shot 2015-11-03 at 7 18 14 pm" src="https://cloud.githubusercontent.com/assets/6226604/10926742/b550bfa8-825f-11e5-86cf-1a45ab591f86.png">

**Comment by carlosmaya** [comment]
@diegobeauroyre  quedamos pendientes del placeholder para youtube

**Comment by diegobeauroyre** [comment]
PLaceholder aquí:

![placeholderdgm](https://cloud.githubusercontent.com/assets/6226604/10989538/0b5882b4-840e-11e5-9c6d-7413f3573f53.png)
