### ISSUE TITLE
Desapareció la liga a la licencia /libreusomx

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#614]
http://datos.gob.mx/libreusomx

**Comment by carlosmaya** [comment]
@rodowi  ¿no es la que quedo en el footer?
![screen shot 2015-11-05 at 5 47 12 pm](https://cloud.githubusercontent.com/assets/2633527/10985254/5aa27308-83e5-11e5-9046-8f1345d2bd70.png)

**Comment by rodowi** [comment]
sí, pero lleva a 404
