### ISSUE TITLE
Filtros

### ISSUE THREAD

**Issue by EduardoClark** [mxabierto/dgm#620]
Al filtrar por categoria en Salud no aparece ningu recurso de la secretaria de salud

![screenshot from 2015-11-06 13-44-52](https://cloud.githubusercontent.com/assets/3537179/11006997/989f8b4e-848c-11e5-8c84-983364a90f8d.png)

**Comment by carlosmaya** [comment]
Hacía falta sincronizar el catálogo de Secretaría de Salud

![screen shot 2015-11-17 at 7 18 14 pm](https://cloud.githubusercontent.com/assets/2633527/11229944/1f6c237c-8d60-11e5-855d-c40701b9afe1.png)
