### ISSUE TITLE
Desaparecieron los redirects?

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#624]
Son importantes para hacer short-urls como datos.gob.mx/agenda2030, había muchas ligas con esto!

https://github.com/mxabierto/dgm/pull/354/files

**Comment by rodowi** [comment]
Este issue no se cierra hasta que se recuperen todos los redirects

https://github.com/mxabierto/dgm/blob/d4038a29a04e83d7aa39750929e07c66a659abac/assets/js/redirects.js

**Comment by chuckcfs** [comment]
actualice el PR para que de momento sólo tome el otro, en cuanto entre agrego los redirects faltantes
