### ISSUE TITLE
La vista de redirect debe mantener el layout de datos.gob.mx

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#628]
Para que se sienta que estamos en el mismo sitio

<img width="1263" alt="screen shot 2015-11-09 at 4 24 52 pm" src="https://cloud.githubusercontent.com/assets/705860/11048690/091009fc-86ff-11e5-9924-0c2d09b5f88f.png">

**Comment by carlosmaya** [comment]
ya no aplica
