### ISSUE TITLE
Las instituciones no se están mostrando

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#629]
<img width="1274" alt="screen shot 2015-11-09 at 4 30 16 pm" src="https://cloud.githubusercontent.com/assets/705860/11048716/3a6cb0f4-86ff-11e5-956c-3aeb4215adac.png">

**Comment by chuckcfs** [comment]
@rodowi de que liga te manda ahí?

**Comment by rodowi** [comment]
Se ve en el screenshot `/instituciones`

**Comment by chuckcfs** [comment]
@rodowi en donde estas entrando?

<img width="1410" alt="screen shot 2015-11-25 at 19 54 29" src="https://cloud.githubusercontent.com/assets/1383865/11413435/62e95918-93ae-11e5-8a0c-737e75e02f37.png">

<img width="1410" alt="screen shot 2015-11-25 at 19 54 36" src="https://cloud.githubusercontent.com/assets/1383865/11413438/66b813ea-93ae-11e5-9ede-28e21436289a.png">

**Comment by chuckcfs** [comment]
y ¿esto no va en ng-ckan? @rodowi cc @carlosmaya

**Comment by rodowi** [comment]
me acaba de pasar en FF

![inst](https://cloud.githubusercontent.com/assets/705860/11413477/0e975774-93af-11e5-819d-a0e69a072428.jpg)

**Comment by rodowi** [comment]
el request URL que falla de organizations es: http://catalogo.datos.gob.mx/api/3/action/organization_show?all_fields=true&id=

**Comment by chuckcfs** [comment]
@rodowi es por el `/` slash al final, tiene que ser http://busca.datos.gob.mx/#/instituciones

**Comment by rodowi** [comment]
por qué no hacen un organization_list?

http://catalogo.datos.gob.mx/api/3/action/organization_list?all_fields=true

**Comment by chuckcfs** [comment]
@rodowi es por el slash, quitalo y hace el `organization_list`

**Comment by rodowi** [comment]
me gustaría dejar abierto este issue porque creo que no podemos ser vulnerables a un `/`. Apuesto a que muchos usuarios llegarán a esa url.

**Comment by chuckcfs** [comment]
resuelto con https://github.com/mxabierto/ng-ckan/pull/276
