### ISSUE TITLE
Quitar margin 20px del logo del navbar

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#645]
<img width="416" alt="screen shot 2015-11-10 at 6 21 13 pm" src="https://cloud.githubusercontent.com/assets/6226604/11080264/e517fdf0-87d7-11e5-896a-1e02f419329e.png">
<img width="248" alt="screen shot 2015-11-10 at 6 21 05 pm" src="https://cloud.githubusercontent.com/assets/6226604/11080263/e515d16a-87d7-11e5-9a34-71f80399f889.png">

**Comment by carlosmaya** [comment]
closed by #662
