### ISSUE TITLE
Agregar pasos para publicar

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#65]
http://datos.gob.mx/publica =>
http://foro.datos.gob.mx/t/cuales-son-los-pasos-para-publicar-en-datos-gob-mx/33

esa liga la vamos a rolar con funcionarios, pero hay que ir pensando en qué menú se puede poner.

**Comment by carlosmaya** [comment]
Se resolvió con la [Guía de Implementación](http://datos.gob.mx/guia)
