### ISSUE TITLE
Las descripciones de los recursos se truncan - debería existir manera de leer toda la descripción

### ISSUE THREAD

**Issue by rodowi** [mxabierto/dgm#651]
http://busca.datos.gob.mx/#/conjuntos/sistema-nacional-de-info-de-calidad-del-aire

<img width="774" alt="screen shot 2015-11-11 at 11 08 10 am" src="https://cloud.githubusercontent.com/assets/705860/11097361/8852354e-8864-11e5-8dae-ce97ec527141.png">

**Comment by carlosmaya** [comment]
se movió a mxabierto/ng-ckan#234
