### ISSUE TITLE
Ajustar las imágenes en el interior de los posts de herramientas

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#653]
Poner `height = 300` y el `max-width` es de 428

![screen shot 2015-11-12 at 9 58 01 am](https://cloud.githubusercontent.com/assets/2633527/11128925/6191e060-8942-11e5-9cf2-bde6beffc4d5.png)

**Comment by diegobeauroyre** [comment]
hay muchas imágenes que no podemos cortar. por eso sugiero lo siguiente: 

Poner un área donde van los screenshots y centrarlos, pongo acá el ejemplo con varios tamaños.

Acá screenshots y el sketch:

https://drive.google.com/folderview?id=0B6xuFjlJEb0NYzdldzZnX0diZ1k&usp=sharing
