### ISSUE TITLE
Descripción se corta en grid de posts impacto/herramientas

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#661]

**Comment by diegobeauroyre** [comment]
<img width="444" alt="screen shot 2015-11-17 at 9 21 28 am" src="https://cloud.githubusercontent.com/assets/6226604/11216336/44e56b04-8d10-11e5-9f03-ec2420dde06c.png">

**Comment by carlosmaya** [comment]
cortar las descripciones que aparecen en el grid a 20 palabras
