### ISSUE TITLE
Broken images en posts

### ISSUE THREAD

**Issue by haxdai** [mxabierto/dgm#675]
En los posts de impacto las imágenes se muestran rotas.

<img width="591" alt="captura de pantalla 2015-11-27 a las 1 45 58 p m" src="https://cloud.githubusercontent.com/assets/7064389/11447574/b3c3b936-950d-11e5-85bf-031df3a67973.png">
<img width="871" alt="captura de pantalla 2015-11-27 a las 1 46 21 p m" src="https://cloud.githubusercontent.com/assets/7064389/11447576/b3c6d86e-950d-11e5-9cf5-82ec5cd03fd7.png">
<img width="892" alt="captura de pantalla 2015-11-27 a las 1 46 46 p m" src="https://cloud.githubusercontent.com/assets/7064389/11447575/b3c63e9a-950d-11e5-8045-3c07100b01df.png">

**Comment by haxdai** [comment]
En realidad parece que es en todos los posts. Saludos

**Comment by carlosmaya** [comment]
gracias @haxdai
