### ISSUE TITLE
Cargar la info de los tweets automaticamente

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#690]
Propongo que en `tweets.son` vayan los ID's de los tweets y con el API de twitter cargar la info

https://dev.twitter.com/rest/reference/get/statuses/show/%3Aid

**Comment by carlosmaya** [comment]
@chuckcfs has podido ver algo sobre este issue? 
quiza podemos solicitar permiso con la cuenta de twitter  @DatosGobMX

**Comment by chuckcfs** [comment]
no más de lo que habíamos platicado, se puede hacer de varias maneras:

- Con un archivo que hay que actualizar como esta ahorita. Desventaja: Hay que actualizar constantemente el archivo.
- Cargando los tweets con el widget oficial. Desventaja: El estilo no puede ser personalizado más allá de algunas customizaciones básicas y no se pueden filtrar los tweets, se mostrarían lo más recientes tal como en un timeline normal.
- Dar de alta una aplicación para usar el API de twitter para jalar los tweets dinámicamente. Desventaja: No hay manera de mostrar una lista "depurada" y hay que crear la aplicación con una cuenta de Twitter.

**Comment by carlosmaya** [comment]
@chuckcfs hay que usar como fuente las cuentas de ` @datosgobmx` y `@opendatacharter`
