### ISSUE TITLE
Agregar encuesta

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#698]

**Comment by Josegarcia89** [comment]
Se podría hacer algo como esto? Como con un botoncito? 

<img width="532" alt="screen shot 2016-01-15 at 12 37 40 pm" src="https://cloud.githubusercontent.com/assets/16548492/12361623/dd441d76-bb84-11e5-913d-d7a391244194.png">

**Comment by carlosmaya** [comment]
@chuckcfs acá te paso la liga de la encuesta

https://docs.google.com/forms/d/1ckzu8nuDpkXGs1pys1ULFFW50Pcoqj4MamfNdqrBK4Q/viewform
