### ISSUE TITLE
No hay "open new tab/window"

### ISSUE THREAD

**Issue by Josegarcia89** [mxabierto/dgm#713]
Cuando quiero ver dos Instituciones a la vez, no hay como abrir una nueva tab. El click derecho no me permite esa opción. Entonces tengo que volver a ingresar a datos.gob.mx, volver a buscar datos > instituciones y buscar de nuevo. 

<img width="324" alt="screen shot 2016-01-27 at 1 39 21 pm" src="https://cloud.githubusercontent.com/assets/16548492/12625982/e7553806-c4fb-11e5-8b35-845add512686.png">

**Comment by chuckcfs** [comment]
@Josegarcia89 esto debe ir en `ng-ckan` y queda resuelto con el PR

https://github.com/mxabierto/ng-ckan/pull/271

Lo cierro
