### ISSUE TITLE
Subscripción

### ISSUE THREAD

**Issue by Josegarcia89** [mxabierto/dgm#721]
Pedir nombre en el proceso de Subscripción. Agregar barrita.

**Comment by chuckcfs** [comment]
@Josegarcia89 no se si se pueda, no por agregar el campo, sino porque la subscripción se hace a través de mailchimp y desconozco si mailchimp permita enviar un campo ademas del nombre, tendrían que checarlo con quien sea que administre la cuenta de datos abierto de mailchimp CC @carlosmaya

**Comment by carlosmaya** [comment]
@Josegarcia89 echale un ojo a esto de mailchimp, quizá con ese se pueda agregar el campo de Nombre para enviarlo dentro del formulario que se tiene actualmente

http://mailchimp.com/features/custom-forms/

**Comment by Josegarcia89** [comment]
Sale, lo checo. gracias

On Mon, Feb 8, 2016 at 2:30 PM ca.ma.ra <notifications@github.com> wrote:

> @Josegarcia89 <https://github.com/Josegarcia89> echale un ojo a esto de
> mailchimp, quizá con ese se pueda agregar el campo de Nombre para enviarlo
> dentro del formulario que se tiene actualmente
>
> http://mailchimp.com/features/custom-forms/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mxabierto/dgm/issues/721#issuecomment-181520013>.
>
-- 


*José García Dobarganes*+52 1 5566100513
bibliografi.co
behance.net/josegarciadobarganes

**Comment by Josegarcia89** [comment]
Chale, nunca encontré eso :/

**Comment by chuckcfs** [comment]
@carlosmaya esto ya lo cerramos ¿no? ya tiene el campo `Nombre` el formulario

**Comment by carlosmaya** [comment]
resuelto en #763
