### ISSUE TITLE
Rollover en Instituciones

### ISSUE THREAD

**Issue by Josegarcia89** [mxabierto/dgm#725]
Se necesitaban poner los nombres completos de las instituciones en un rollover al pasar por la imagen y no solo sus siglas. Les paso la lista de todos modos. Creo que RPizzuto había dicho que él lo iba a hacer, pero según yo él no ve esto ¿o sí? La lista la tiene él, eso sí.

**Comment by carlosmaya** [comment]
la conversación de esto esta por acá mxabierto/ng-ckan#227

**Comment by carlosmaya** [comment]
es el siguiente en la lista, acá esta el roadmap

https://waffle.io/mxabierto/ng-ckan
