### ISSUE TITLE
Ordenar posts del mas reciente al mas antiguo

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#847]

**Comment by chuckcfs** [comment]
@carlosmaya esto así está ¿qué no?

**Comment by carlosmaya** [comment]
a mi me aparecen ordenados alfabeticamente, por ejemplo

* Datatron  es del  1 noviembre, 2013 
* Dataton es del 27 julio, 2014
* Datos abiertos Jalisco es del 28 abril, 2016
* Datos abiertos e igualdad de genero es del 8 marzo, 2016

y aparecen todas seguidas

![screen shot 2016-06-13 at 15 28 31](https://cloud.githubusercontent.com/assets/2633527/16022136/f82126a8-317b-11e6-9bd9-97965bc30b29.png)
