### ISSUE TITLE
Ajustar espacio entre tabs para sección de datos en landing

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/dgm#869]
![screen_shot_2016-06-16_at_15_57_16](https://cloud.githubusercontent.com/assets/2633527/16133171/14d642e4-33dc-11e6-84b0-d8d307711432.png)

**Comment by chuckcfs** [comment]
@carlosmaya cuál cambio, el lateral o el de abajo?

**Comment by carlosmaya** [comment]
el lateral
