### ISSUE TITLE
Alinear cajas de blogs

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#981]
<img width="1206" alt="screen shot 2016-06-24 at 11 47 09 am" src="https://cloud.githubusercontent.com/assets/6226604/16344696/6e62fa0a-3a03-11e6-874d-967f1ae4bdfa.png">

**Comment by chuckcfs** [comment]
@diegobeauroyre @carlosmaya es un asunto del tamaño de las imágenes

![screen shot 2016-06-24 at 12 06 46](https://cloud.githubusercontent.com/assets/1383865/16344822/46beebfc-3a04-11e6-90f6-f815184dfe46.png)

![screen shot 2016-06-24 at 12 06 59](https://cloud.githubusercontent.com/assets/1383865/16344824/4897fbda-3a04-11e6-98b2-885ebd7cd1d0.png)
