### ISSUE TITLE
Alinear navbar con breadcrumb

### ISSUE THREAD

**Issue by diegobeauroyre** [mxabierto/dgm#985]
<img width="286" alt="screen shot 2016-06-27 at 12 16 00 pm" src="https://cloud.githubusercontent.com/assets/6226604/16391175/968bf3e6-3c6b-11e6-982a-d42f15a463ed.png">
<img width="424" alt="screen shot 2016-06-27 at 12 34 47 pm" src="https://cloud.githubusercontent.com/assets/6226604/16391174/968844e4-3c6b-11e6-898a-2c8569d3008f.png">

**Comment by chuckcfs** [comment]
@carlosmaya hace falta hacer un `bower update` para tomar la versión más reciente del navbar

**Comment by carlosmaya** [comment]
se solucionó con mxabierto/dgm-navbar#19
